version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    volumes:
      - ${PWD}/server/config.ini:/config.ini
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - SERVER_AGENCY_COUNT=5
    networks:
      - testing_net
  client1:
    container_name: client1
    image: client:latest
    volumes:
      - ${PWD}/client/config.ini:/config.ini
      - ${PWD}/.data/agency-1.csv:/agency.csv
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      - server
  client2:
    container_name: client2
    image: client:latest
    volumes:
      - ${PWD}/client/config.ini:/config.ini
      - ${PWD}/.data/agency-2.csv:/agency.csv
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      - server
  client3:
    container_name: client3
    image: client:latest
    volumes:
      - ${PWD}/client/config.ini:/config.ini
      - ${PWD}/.data/agency-3.csv:/agency.csv
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=3
      - CLI_LOG_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      - server
  client4:
    container_name: client4
    image: client:latest
    volumes:
      - ${PWD}/client/config.ini:/config.ini
      - ${PWD}/.data/agency-4.csv:/agency.csv
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=4
      - CLI_LOG_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      - server
  client5:
    container_name: client5
    image: client:latest
    volumes:
      - ${PWD}/client/config.ini:/config.ini
      - ${PWD}/.data/agency-5.csv:/agency.csv
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=5
      - CLI_LOG_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      - server
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
