version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    volumes:
      - ${PWD}/server/config.ini:/config.ini
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
    networks:
      - testing_net
  client1:
    container_name: client1
    image: client:latest
    volumes:
      - ${PWD}/client/config.ini:/config.ini
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=INFO
      - NOMBRE=Ariel
      - APELLIDO=Liniers
      - DOCUMENTO=34549220
      - NACIMIENTO=1983-11-03
      - NUMERO=17231
    networks:
      - testing_net
    depends_on:
      - server
  client2:
    container_name: client2
    image: client:latest
    volumes:
      - ${PWD}/client/config.ini:/config.ini
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=INFO
      - NOMBRE=Juan
      - APELLIDO=Gonzalez
      - DOCUMENTO=16262417
      - NACIMIENTO=1972-10-10
      - NUMERO=31116
    networks:
      - testing_net
    depends_on:
      - server
  client3:
    container_name: client3
    image: client:latest
    volumes:
      - ${PWD}/client/config.ini:/config.ini
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=3
      - CLI_LOG_LEVEL=INFO
      - NOMBRE=Harold
      - APELLIDO=Diaz
      - DOCUMENTO=11943245
      - NACIMIENTO=2002-09-17
      - NUMERO=1072
    networks:
      - testing_net
    depends_on:
      - server
  client4:
    container_name: client4
    image: client:latest
    volumes:
      - ${PWD}/client/config.ini:/config.ini
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=4
      - CLI_LOG_LEVEL=INFO
      - NOMBRE=María
      - APELLIDO=Serrano
      - DOCUMENTO=9400289
      - NACIMIENTO=1993-03-25
      - NUMERO=5726
    networks:
      - testing_net
    depends_on:
      - server
  client5:
    container_name: client5
    image: client:latest
    volumes:
      - ${PWD}/client/config.ini:/config.ini
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=5
      - CLI_LOG_LEVEL=INFO
      - NOMBRE=Beatriz
      - APELLIDO=Cardinali
      - DOCUMENTO=42924206
      - NACIMIENTO=1996-03-01
      - NUMERO=1440
    networks:
      - testing_net
    depends_on:
      - server
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
