version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    volumes:
      - ${PWD}/server/config.ini:/config.ini
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
  client1:
    container_name: client1
    image: client:latest
    volumes:
      - ${PWD}/client/config.ini:/config.ini
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Beatriz
      - APELLIDO=Rivadavia
      - DOCUMENTO=34543373
      - NACIMIENTO=1999-12-27
      - NUMERO=25552
    networks:
      - testing_net
    depends_on:
      - server
  client2:
    container_name: client2
    image: client:latest
    volumes:
      - ${PWD}/client/config.ini:/config.ini
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Tomas
      - APELLIDO=Gomez
      - DOCUMENTO=42742981
      - NACIMIENTO=1996-09-08
      - NUMERO=1187
    networks:
      - testing_net
    depends_on:
      - server
  client3:
    container_name: client3
    image: client:latest
    volumes:
      - ${PWD}/client/config.ini:/config.ini
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=3
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Hipólito
      - APELLIDO=Gomez
      - DOCUMENTO=11466741
      - NACIMIENTO=1992-12-08
      - NUMERO=3657
    networks:
      - testing_net
    depends_on:
      - server
  client4:
    container_name: client4
    image: client:latest
    volumes:
      - ${PWD}/client/config.ini:/config.ini
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=4
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Juan
      - APELLIDO=Rivadavia
      - DOCUMENTO=18444133
      - NACIMIENTO=2000-04-01
      - NUMERO=18790
    networks:
      - testing_net
    depends_on:
      - server
  client5:
    container_name: client5
    image: client:latest
    volumes:
      - ${PWD}/client/config.ini:/config.ini
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=5
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Ariel
      - APELLIDO=Bedoya
      - DOCUMENTO=36884529
      - NACIMIENTO=1983-07-26
      - NUMERO=29284
    networks:
      - testing_net
    depends_on:
      - server
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
